
package com.turismouy.generados;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "InscripcionCapacidadExcedidaException", targetNamespace = "http://presentacion.src/")
public class InscripcionCapacidadExcedidaException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private InscripcionCapacidadExcedidaException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public InscripcionCapacidadExcedidaException_Exception(String message, InscripcionCapacidadExcedidaException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public InscripcionCapacidadExcedidaException_Exception(String message, InscripcionCapacidadExcedidaException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: src.presentacion.InscripcionCapacidadExcedidaException
     */
    public InscripcionCapacidadExcedidaException getFaultInfo() {
        return faultInfo;
    }

}
