
package com.turismouy.generados;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "Publicador", targetNamespace = "http://presentacion.src/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Publicador {


    /**
     * 
     * @param arg0
     * @return
     *     returns src.presentacion.DtInscripciones
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://presentacion.src/Publicador/obtenerDTInscripcionesAsociadasTuristaRequest", output = "http://presentacion.src/Publicador/obtenerDTInscripcionesAsociadasTuristaResponse")
    public DtInscripciones obtenerDTInscripcionesAsociadasTurista(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @return
     *     returns src.presentacion.DtActividades
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://presentacion.src/Publicador/obtenerActividadesTuristicasAgregadasRequest", output = "http://presentacion.src/Publicador/obtenerActividadesTuristicasAgregadasResponse")
    public DtActividades obtenerActividadesTuristicasAgregadas();

    /**
     * 
     * @param arg0
     * @return
     *     returns src.presentacion.DtActividades
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://presentacion.src/Publicador/obtenerDTActividadesConfirmadasCategoriaRequest", output = "http://presentacion.src/Publicador/obtenerDTActividadesConfirmadasCategoriaResponse")
    public DtActividades obtenerDTActividadesConfirmadasCategoria(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns src.presentacion.DtActividades
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://presentacion.src/Publicador/obtenerDTActividadesConfirmadasDeptoRequest", output = "http://presentacion.src/Publicador/obtenerDTActividadesConfirmadasDeptoResponse")
    public DtActividades obtenerDTActividadesConfirmadasDepto(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @return
     *     returns src.presentacion.DtUsuarios
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://presentacion.src/Publicador/obtenerDTUsuariosRequest", output = "http://presentacion.src/Publicador/obtenerDTUsuariosResponse")
    public DtUsuarios obtenerDTUsuarios();

    /**
     * 
     * @param arg0
     * @return
     *     returns src.presentacion.DtActividadTuristica
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://presentacion.src/Publicador/obtenerDTActividadTuristicaRequest", output = "http://presentacion.src/Publicador/obtenerDTActividadTuristicaResponse")
    public DtActividadTuristica obtenerDTActividadTuristica(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns src.presentacion.DtSalidas
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://presentacion.src/Publicador/obtenerDTSalidasTuristicasRequest", output = "http://presentacion.src/Publicador/obtenerDTSalidasTuristicasResponse")
    public DtSalidas obtenerDTSalidasTuristicas(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @throws ExcepcionAltaSalida_Exception
     */
    @WebMethod
    @Action(input = "http://presentacion.src/Publicador/ingresarDatosSalidaTuristicaRequest", output = "http://presentacion.src/Publicador/ingresarDatosSalidaTuristicaResponse", fault = {
        @FaultAction(className = ExcepcionAltaSalida_Exception.class, value = "http://presentacion.src/Publicador/ingresarDatosSalidaTuristica/Fault/ExcepcionAltaSalida")
    })
    public void ingresarDatosSalidaTuristica(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        DtSalidaTuristica arg1)
        throws ExcepcionAltaSalida_Exception
    ;

    /**
     * 
     */
    @WebMethod
    @Action(input = "http://presentacion.src/Publicador/cancelarInscripcionRequest", output = "http://presentacion.src/Publicador/cancelarInscripcionResponse")
    public void cancelarInscripcion();

    /**
     * 
     * @param arg0
     * @param arg1
     * @throws ExcepcionModificarSalida_Exception
     */
    @WebMethod
    @Action(input = "http://presentacion.src/Publicador/modificarDatosSalidaTuristicaRequest", output = "http://presentacion.src/Publicador/modificarDatosSalidaTuristicaResponse", fault = {
        @FaultAction(className = ExcepcionModificarSalida_Exception.class, value = "http://presentacion.src/Publicador/modificarDatosSalidaTuristica/Fault/ExcepcionModificarSalida")
    })
    public void modificarDatosSalidaTuristica(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        DtSalidaTuristica arg1)
        throws ExcepcionModificarSalida_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns src.presentacion.DtSalidaTuristica
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://presentacion.src/Publicador/obtenerDTSalidaTuristicaRequest", output = "http://presentacion.src/Publicador/obtenerDTSalidaTuristicaResponse")
    public DtSalidaTuristica obtenerDTSalidaTuristica(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns src.presentacion.DtUsuarioExtendido
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://presentacion.src/Publicador/obtenerUsuarioPorIDRequest", output = "http://presentacion.src/Publicador/obtenerUsuarioPorIDResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://presentacion.src/Publicador/obtenerUsuarioPorID/Fault/UsuarioNoExisteException")
    })
    public DtUsuarioExtendido obtenerUsuarioPorID(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @return
     *     returns src.presentacion.DtActividades
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://presentacion.src/Publicador/obtenerDTActividadesConfirmadasRequest", output = "http://presentacion.src/Publicador/obtenerDTActividadesConfirmadasResponse")
    public DtActividades obtenerDTActividadesConfirmadas();

    /**
     * 
     * @return
     *     returns src.presentacion.DtDepartamentos
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://presentacion.src/Publicador/obtenerDTDepartamentosRequest", output = "http://presentacion.src/Publicador/obtenerDTDepartamentosResponse")
    public DtDepartamentos obtenerDTDepartamentos();

    /**
     * 
     * @return
     *     returns src.presentacion.DtActividades
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://presentacion.src/Publicador/obtenerDTActividadesRequest", output = "http://presentacion.src/Publicador/obtenerDTActividadesResponse")
    public DtActividades obtenerDTActividades();

    /**
     * 
     * @param arg0
     * @param arg1
     * @throws ActividadRepetidaException_Exception
     */
    @WebMethod
    @Action(input = "http://presentacion.src/Publicador/aceptarAltaActividadRequest", output = "http://presentacion.src/Publicador/aceptarAltaActividadResponse", fault = {
        @FaultAction(className = ActividadRepetidaException_Exception.class, value = "http://presentacion.src/Publicador/aceptarAltaActividad/Fault/ActividadRepetidaException")
    })
    public void aceptarAltaActividad(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        DtActividadExtendida arg1)
        throws ActividadRepetidaException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns src.presentacion.DtUsuarioExtendido
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://presentacion.src/Publicador/obtenerDTUsuarioExtendidoRequest", output = "http://presentacion.src/Publicador/obtenerDTUsuarioExtendidoResponse")
    public DtUsuarioExtendido obtenerDTUsuarioExtendido(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns src.presentacion.DtSalidas
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://presentacion.src/Publicador/obtenerDTSalidasVigentesRequest", output = "http://presentacion.src/Publicador/obtenerDTSalidasVigentesResponse")
    public DtSalidas obtenerDTSalidasVigentes(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @return
     *     returns src.presentacion.DtProveedores
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://presentacion.src/Publicador/obtenerDTProveedoresRequest", output = "http://presentacion.src/Publicador/obtenerDTProveedoresResponse")
    public DtProveedores obtenerDTProveedores();

    /**
     * 
     * @param arg0
     * @throws UsuarioRepetidoException_Exception
     */
    @WebMethod
    @Action(input = "http://presentacion.src/Publicador/aceptarAltaProveedorRequest", output = "http://presentacion.src/Publicador/aceptarAltaProveedorResponse", fault = {
        @FaultAction(className = UsuarioRepetidoException_Exception.class, value = "http://presentacion.src/Publicador/aceptarAltaProveedor/Fault/UsuarioRepetidoException")
    })
    public void aceptarAltaProveedor(
        @WebParam(name = "arg0", partName = "arg0")
        DtProveedor arg0)
        throws UsuarioRepetidoException_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws SalidasVigentesException_Exception
     */
    @WebMethod
    @Action(input = "http://presentacion.src/Publicador/finalizarActividadRequest", output = "http://presentacion.src/Publicador/finalizarActividadResponse", fault = {
        @FaultAction(className = SalidasVigentesException_Exception.class, value = "http://presentacion.src/Publicador/finalizarActividad/Fault/SalidasVigentesException")
    })
    public void finalizarActividad(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws SalidasVigentesException_Exception
    ;

    /**
     * 
     * @return
     *     returns src.presentacion.DtSalidas
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://presentacion.src/Publicador/obtenerDTSalidasRequest", output = "http://presentacion.src/Publicador/obtenerDTSalidasResponse")
    public DtSalidas obtenerDTSalidas();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://presentacion.src/Publicador/rechazarActividadRequest", output = "http://presentacion.src/Publicador/rechazarActividadResponse")
    public void rechazarActividad(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns src.presentacion.DtCategoria
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://presentacion.src/Publicador/obtenerDTCategoriaRequest", output = "http://presentacion.src/Publicador/obtenerDTCategoriaResponse")
    public DtCategoria obtenerDTCategoria(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://presentacion.src/Publicador/confirmarActividadRequest", output = "http://presentacion.src/Publicador/confirmarActividadResponse")
    public void confirmarActividad(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @throws InscripcionCapacidadExcedidaException_Exception
     * @throws InscripcionYaExisteException_Exception
     */
    @WebMethod
    @Action(input = "http://presentacion.src/Publicador/aceptarInscripcionRequest", output = "http://presentacion.src/Publicador/aceptarInscripcionResponse", fault = {
        @FaultAction(className = InscripcionYaExisteException_Exception.class, value = "http://presentacion.src/Publicador/aceptarInscripcion/Fault/InscripcionYaExisteException"),
        @FaultAction(className = InscripcionCapacidadExcedidaException_Exception.class, value = "http://presentacion.src/Publicador/aceptarInscripcion/Fault/InscripcionCapacidadExcedidaException")
    })
    public void aceptarInscripcion(
        @WebParam(name = "arg0", partName = "arg0")
        DtInscripcion arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2)
        throws InscripcionCapacidadExcedidaException_Exception, InscripcionYaExisteException_Exception
    ;

    /**
     * 
     * @return
     *     returns src.presentacion.DtTuristas
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://presentacion.src/Publicador/obtenerDTTuristasRequest", output = "http://presentacion.src/Publicador/obtenerDTTuristasResponse")
    public DtTuristas obtenerDTTuristas();

    /**
     * 
     * @param arg0
     * @throws UsuarioRepetidoException_Exception
     */
    @WebMethod
    @Action(input = "http://presentacion.src/Publicador/aceptarAltaTuristaRequest", output = "http://presentacion.src/Publicador/aceptarAltaTuristaResponse", fault = {
        @FaultAction(className = UsuarioRepetidoException_Exception.class, value = "http://presentacion.src/Publicador/aceptarAltaTurista/Fault/UsuarioRepetidoException")
    })
    public void aceptarAltaTurista(
        @WebParam(name = "arg0", partName = "arg0")
        DtTurista arg0)
        throws UsuarioRepetidoException_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     */
    @WebMethod
    @Action(input = "http://presentacion.src/Publicador/seguirONoAUsuarioRequest", output = "http://presentacion.src/Publicador/seguirONoAUsuarioResponse")
    public void seguirONoAUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @throws DepartamentoRepetidoException_Exception
     */
    @WebMethod
    @Action(input = "http://presentacion.src/Publicador/altaDepartamentoRequest", output = "http://presentacion.src/Publicador/altaDepartamentoResponse", fault = {
        @FaultAction(className = DepartamentoRepetidoException_Exception.class, value = "http://presentacion.src/Publicador/altaDepartamento/Fault/DepartamentoRepetidoException")
    })
    public void altaDepartamento(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2)
        throws DepartamentoRepetidoException_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     */
    @WebMethod
    @Action(input = "http://presentacion.src/Publicador/ingresarActividadTuristicaRequest", output = "http://presentacion.src/Publicador/ingresarActividadTuristicaResponse")
    public void ingresarActividadTuristica(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns src.presentacion.DtActividadExtendida
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://presentacion.src/Publicador/obtenerDTActividadExtendidoRequest", output = "http://presentacion.src/Publicador/obtenerDTActividadExtendidoResponse")
    public DtActividadExtendida obtenerDTActividadExtendido(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns src.presentacion.DtPaqueteActividadExtendido
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://presentacion.src/Publicador/obtenerPaqueteExtendidoRequest", output = "http://presentacion.src/Publicador/obtenerPaqueteExtendidoResponse")
    public DtPaqueteActividadExtendido obtenerPaqueteExtendido(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @return
     *     returns src.presentacion.DtCategorias
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://presentacion.src/Publicador/obtenerDTCategoriasRequest", output = "http://presentacion.src/Publicador/obtenerDTCategoriasResponse")
    public DtCategorias obtenerDTCategorias();

    /**
     * 
     * @return
     *     returns src.presentacion.DtProveedorExtendido
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://presentacion.src/Publicador/publicarProveedorExtendidoRequest", output = "http://presentacion.src/Publicador/publicarProveedorExtendidoResponse")
    public DtProveedorExtendido publicarProveedorExtendido();

    /**
     * 
     * @param arg0
     * @throws ExcepcionAltaCategoria_Exception
     */
    @WebMethod
    @Action(input = "http://presentacion.src/Publicador/aceptarAltaCategoriaRequest", output = "http://presentacion.src/Publicador/aceptarAltaCategoriaResponse", fault = {
        @FaultAction(className = ExcepcionAltaCategoria_Exception.class, value = "http://presentacion.src/Publicador/aceptarAltaCategoria/Fault/ExcepcionAltaCategoria")
    })
    public void aceptarAltaCategoria(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws ExcepcionAltaCategoria_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns src.presentacion.DtActividadesExtendidas
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://presentacion.src/Publicador/obtenerDTActividadesExtendidoRequest", output = "http://presentacion.src/Publicador/obtenerDTActividadesExtendidoResponse")
    public DtActividadesExtendidas obtenerDTActividadesExtendido(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @return
     *     returns src.presentacion.DtTuristaExtendido
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://presentacion.src/Publicador/publicarTuristaExtendidoRequest", output = "http://presentacion.src/Publicador/publicarTuristaExtendidoResponse")
    public DtTuristaExtendido publicarTuristaExtendido();

    /**
     * 
     * @param arg0
     * @throws PaqueteRepetidoException_Exception
     */
    @WebMethod
    @Action(input = "http://presentacion.src/Publicador/crearNuevoPaqueteRequest", output = "http://presentacion.src/Publicador/crearNuevoPaqueteResponse", fault = {
        @FaultAction(className = PaqueteRepetidoException_Exception.class, value = "http://presentacion.src/Publicador/crearNuevoPaquete/Fault/PaqueteRepetidoException")
    })
    public void crearNuevoPaquete(
        @WebParam(name = "arg0", partName = "arg0")
        DtPaqueteActividad arg0)
        throws PaqueteRepetidoException_Exception
    ;

}
