
package com.turismouy.generados;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "ExcepcionAltaCategoria", targetNamespace = "http://presentacion.src/")
public class ExcepcionAltaCategoria_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ExcepcionAltaCategoria faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ExcepcionAltaCategoria_Exception(String message, ExcepcionAltaCategoria faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public ExcepcionAltaCategoria_Exception(String message, ExcepcionAltaCategoria faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: src.presentacion.ExcepcionAltaCategoria
     */
    public ExcepcionAltaCategoria getFaultInfo() {
        return faultInfo;
    }

}
